// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/game.proto

package proto.commons;

public interface HumanReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HumanReply)
    com.google.protobuf.MessageOrBuilder {
}
