// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/game.proto

package proto.commons;

public interface HumanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HumanRequest)
    com.google.protobuf.MessageOrBuilder {
}
